[build]
builder = "nixpacks"
buildCommand = "pip install --no-cache-dir -r requirements.txt"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[variables]
PYTHON_VERSION = "3.10"
PIP_NO_CACHE_DIR = "1"
PIP_DISABLE_PIP_VERSION_CHECK = "1"
PYTORCH_BUILD_VERSION = "2.1.0"
PYTORCH_BUILD_NUMBER = "1"
# Railway memory optimization
PYTHONUNBUFFERED = "1"
PYTHONDONTWRITEBYTECODE = "1"